# Generated by Django 5.2.12 on 2026-04-23 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
        ("stores", "0002_alter_store_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads",
                to="stores.store",
            ),
        ),
    ]
