# Generated by Django 5.2.12 on 2026-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
